import {
  LucideIcon,
  TicketPercent,
  PackageOpen,
  ShieldAlert,
  Settings2,
  CircleEllipsis,
  Settings,
  GitBranch,
  FileText,
  Shield,
  AppWindow,
  Flag,
  Star,
  Coins,
  Key,
  Podcast,
  Calendar,
  LayoutDashboard,
  Building,
  Layers,
  Users,
  FolderCode,
  UserCircle,
  User,
  Archive,
  History,
  Share2,
  FileSearch,
  MessageCircle,
  Grid,
  Cog,
  Database,
  Hash,
  Workflow,
  MapPin,
  Map,
  Activity,
  UserCog,
  Group,
  Boxes,
  Box,
  Ticket,
  Layers2,
  Clock,
  Ruler,
  Users2,
  Warehouse,
  Sliders,
  Calculator,
  Scale,
  Grid3x3,
  FileBarChart,
  List,
  CalendarClock,
  AlignLeft,
  CheckCircle,
  ListCheck,
  Cpu,
  Link,
  Banknote,
  Fuel,
  Store,
  Handshake,
  CalendarCheck,
  File,
  Check,
  Pause,
  CircleArrowRight,
  ChartLine,
  FileCode,
  BadgeDollarSign,
  SquareKanban,
  Clipboard,
  ClipboardCheck,
  ShoppingCart,
  Package,
  Tags,
  Edit,
  Truck,
  Droplet,
  HandHelping,
  Server,
  Type,
  CircleArrowDown,
  ListPlus
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  'ticket-percenet': TicketPercent,
  'package-open': PackageOpen,
  'shield-alert': ShieldAlert,
  'settings-2': Settings2,
  'circle-ellipsis': CircleEllipsis,
  settings: Settings,
  'git-branch': GitBranch,
  'file-text': FileText,
  shield: Shield,
  'app-window': AppWindow,
  flag: Flag,
  star: Star,
  coins: Coins,
  key: Key,
  podcast: Podcast,
  calendar: Calendar,
  'layout-dashboard': LayoutDashboard,
  building: Building,
  layers: Layers,
  users: Users,
  'folder-code': FolderCode,
  'user-circle': UserCircle,
  user: User,
  archive: Archive,
  history: History,
  'share-2': Share2,
  'file-search': FileSearch,
  'message-circle': MessageCircle,
  grid: Grid,
  cog: Cog,
  database: Database,
  hash: Hash,
  workflow: Workflow,
  'map-pin': MapPin,
  map: Map,
  activity: Activity,
  'user-cog': UserCog,
  group: Group,
  boxes: Boxes,
  box: Box,
  ticket: Ticket,
  'layers-2': Layers2,
  clock: Clock,
  ruler: Ruler,
  'users-2': Users2,
  warehouse: Warehouse,
  sliders: Sliders,
  calculator: Calculator,
  scale: Scale,
  'grid-3x3': Grid3x3,
  'file-bar-chart': FileBarChart,
  list: List,
  'calendar-clock': CalendarClock,
  'align-left': AlignLeft,
  'check-circle': CheckCircle,
  'list-check': ListCheck,
  cpu: Cpu,
  link: Link,
  banknote: Banknote,
  fuel: Fuel,
  store: Store,
  handshake: Handshake,
  'calendar-check': CalendarCheck,
  file: File,
  check: Check,
  pause: Pause,
  'circle-arrow-right': CircleArrowRight,
  'chart-line': ChartLine,
  'file-code': FileCode,
  'badge-dollar-sign': BadgeDollarSign,
  'square-kanban': SquareKanban,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'shopping-cart': ShoppingCart,
  package: Package,
  tags: Tags,
  edit: Edit,
  truck: Truck,
  droplet: Droplet,
  'hand-helping': HandHelping,
  server: Server,
  type: Type,
  'circle-arrow-down': CircleArrowDown,
  'list-plus': ListPlus
};
